name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
          export_default_credentials: true
